### PR TITLE
Use Flow (0.11), instead of the non-existing GenStage Experimental.Flow.

### PR DESCRIPTION
**Pull request by theredcoder**
Also, fix vec_apply/3 so LinearAlgebra.substract and LinearAlgebra.multiply returns a Stream (not a Flow) and Flow.from_enumerable works once more.

### CODE REVIEW

**Comment by theredcoder** [comment]
Check out these links for further details:
- [GenStage CHANGELOG](https://github.com/elixir-lang/gen_stage/blob/master/CHANGELOG.md)
- [Further details about changes to Flow.from_enumerable/2](https://github.com/elixir-lang/flow/blob/v0.11.0/lib/flow.ex#L447)

**Comment by safwank** [comment]
@theredcoder Thanks. I'm currently on vacation. Will merge the PR when I get back.

**Comment by safwank** [comment]
Merged and released in [v0.4.2](https://github.com/safwank/Numerix/releases/tag/v0.4.2). Thanks for the PR!

**Comment by theredcoder** [comment]
@safwank You're welcome! Thank you for Numerix.

**Pull request merged**
